### ISSUE TITLE
Dulicate skill.

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#19] opened 2015-04-22 22:44 UTC
For some reason I cannot add a camping skill to my profile page. It claims I am attempting to add a duplicate skill.  The screen shot looks as though I was trying to enter piano but before I clicked submit it was saying camping
![image](https://cloud.githubusercontent.com/assets/8978368/7287095/2d9d9e0a-e917-11e4-84ed-b7cd7e907d0d.png)

**Comment by anthonytokosky** [comment] 2015-04-26 21:03
I think this is resolved. I cannot reproduce, so closing for now. If we run into this issue again, we can reopen.

**Closed as completed by anthonytokosky** 2015-04-26 21:03 UTC
